name: LMS Automation

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 2 * * *"   # runs daily (optional)

jobs:
  run-job:
    runs-on: self-hosted   # ✅ IMPORTANT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run main script
        run: node app2.js

      - name: Run merge
        run: node excelMerger.js
